# taken from https://github.com/MikeSchulze/gdUnit4/blob/master/.github/workflows/ci-pr-example.yml
name: ci-pr-example
run-name: ${{ github.head_ref || github.ref_name }}-ci-pr-example

on:
  # pull_request:
  #  paths-ignore:
  #    - '**.yml'
  #    - '**.md'
  workflow_dispatch:

env:
  GODOT_VERSION: 4.2.2
  EXPORT_NAME: GodotAutoBuild

concurrency:
  group: ci-pr-example${{ github.event.number }}
  cancel-in-progress: true


jobs:
  unit-test:
    name: "CI Unit Test"
    runs-on: 'ubuntu-22.04'
    timeout-minutes: 10 # The overall timeout
    permissions:
      actions: write
      checks: write
      contents: write
      pull-requests: write
      statuses: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          
      - name: GDUnit4-Action
        uses: MikeSchulze/gdUnit4-action@v1.1.1
        with:
          godot-version: '4.2.2'
          paths: |
            res://test/
          timeout: 5
          report-name: test_report.xml
  
  windows-build:
    name: Windows Build
    runs-on: ubuntu-20.04
    needs: [unit-test]
    container:
      image: barichello/godot-ci:4.2.2

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          godot --headless --verbose --export-release "Windows Desktop" build/windows/$EXPORT_NAME.exe
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: Builds/Windows          
    
